apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: juice-shop
  namespace: juice-shop
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: juice-shop
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
